# Archivo: .github/workflows/metrics.yml
name: GitHub Metrics
on:
  # Se ejecuta cada 6 horas
  schedule:
    - cron: "0 */6 * * *"
  # Permite ejecutarlo manualmente desde la pestaña Actions
  workflow_dispatch:
  # Se ejecuta también cuando haces un push a la rama main
  push:
    branches:
      - main
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
     contents: write
    steps:
      # --- PASO 1: Genera la imagen de Logros ---
      - name: Generate Achievements SVG
        uses: lowlighter/metrics@latest
        with:
          user: CandyGZ
          token: ${{ secrets.METRICS_TOKEN }}
          filename: achievements.svg
          base: ""
          plugin_achievements: yes
          plugin_achievements_threshold: S
          plugin_achievements_secrets: yes
          plugin_achievements_display: detailed
          plugin_achievements_limit: 1
          config_timezone: America/Mexico_City

      # --- PASO 2: Genera la imagen de Lenguajes ---
      - name: Generate Languages SVG
        uses: lowlighter/metrics@latest
        with:
          user: CandyGZ
          base: ""
          plugin_achievements: yes
          plugin_achievements_only: >-
            polyglot, stargazer, sponsor, deployer, member, maintainer, developer,
            scripter, packager, explorer, infographile, manager
          plugin_achievements_display: compact
          plugin_achievements_threshold: X

     
      # --- PASO 2: Genera la imagen de Lenguajes ---
      - name: Recently starred
        uses: lowlighter/metrics@latest
        with:
          user: CandyGZ
          filename: metrics.plugin.stars.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_stars: yes
          plugin_stars_limit: 3

        
